wso2/cdmf-agent-android

client/client/build.gradle
client/client/src/main/AndroidManifest.xml
client/client/src/main/java/org/wso2/iot/agent/AlertActivity.java
client/client/src/main/java/org/wso2/iot/agent/AuthenticationActivity.java
client/client/src/main/java/org/wso2/iot/agent/SplashActivity.java
client/client/src/main/java/org/wso2/iot/agent/services/DeviceStartupIntentReceiver.java
client/client/src/main/java/org/wso2/iot/agent/services/MessageProcessor.java
client/client/src/main/java/org/wso2/iot/agent/utils/Constants.java
client/client/src/main/res/layout/activity_pin_code.xml
client/client/src/main/res/values/strings.xml
client/iDPProxy/build.gradle
client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/APIController.java
client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/AccessTokenHandler.java
client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/IdentityProxy.java
client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/RefreshTokenHandler.java
client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/beans/Token.java
client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/clients/OAuthSSLClient.java
client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/utils/Constants.java
client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/utils/ServerUtilities.java

- Add sign in on token validation failure 
- Add descriptive UI for PIN entry 
- Device muting after ring operation issue is fixed 
- Fix time zone issue in token expiry check

Fixes and Improvements

---

client/client/src/main/AndroidManifest.xml
client/client/src/main/java/org/wso2/iot/agent/KioskActivity.java
client/client/src/main/java/org/wso2/iot/agent/events/listeners/KioskAppInstallationListener.java
client/client/src/main/java/org/wso2/iot/agent/utils/Constants.java

Separated the kisok app install broadcast receiver. This fixes the issue of not receiving app install broadcasts when the kiosk app is being used.

Separated the kisok app install broadcast receiver

---

client/client/src/main/java/org/wso2/iot/agent/activities/AuthenticationActivity.java

Added device admin prompt when using Mutual SSL authentication client.

Added device admin prompt when using MSSL auth

---

client/build.gradle
client/client/src/main/java/org/wso2/iot/agent/activities/AuthenticationActivity.java

fixes https://github.com/wso2/product-iots/issues/1121

Fix the issue arose when signing in with admin credentials in worker profile

---

client/client/src/main/java/org/wso2/iot/agent/activities/AuthenticationActivity.java

fixes https://github.com/wso2/product-iots/issues/1153

Fixes enrollment issue in clustered environment

---

client/client/src/main/AndroidManifest.xml
client/client/src/main/java/org/wso2/iot/agent/api/ApplicationManager.java
client/client/src/main/res/xml/provider_paths.xml

Fixed wso2/product-iots#1317
Fixed apk installation from Store in android 7 (api 24) and higher.

Fixed product-iots#1317

---

client/client/src/main/java/org/wso2/iot/agent/activities/AlreadyRegisteredActivity.java
client/client/src/main/java/org/wso2/iot/agent/activities/EnableProfileActivity.java

Fixed https://github.com/wso2/product-iots/issues/1332

Fixing product-iots#1332

---

client/client/src/main/java/org/wso2/iot/agent/events/listeners/ApplicationStateListener.java
client/client/src/main/java/org/wso2/iot/agent/services/PolicyComplianceChecker.java
client/client/src/main/java/org/wso2/iot/agent/services/PolicyRevokeHandler.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManager.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerBYOD.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerWorkProfile.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationProcessor.java
client/client/src/main/java/org/wso2/iot/agent/utils/Constants.java
client/client/src/main/res/values/strings.xml

Fixes Work-profile scenario of the issue https://github.com/wso2/product-iots/issues/1331

Fix app white-listing in Android work-profile.

---

client/client/src/main/java/org/wso2/iot/agent/events/listeners/ApplicationStateListener.java
client/client/src/main/java/org/wso2/iot/agent/services/PolicyRevokeHandler.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManager.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerBYOD.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerDeviceOwner.java

Fixes COPE and DeviceOwner scenarios in https://github.com/wso2/product-iots/issues/1331

Fix for app white-listing issue in COPE and Device owner scenarios.

---

client/client/src/main/java/org/wso2/iot/agent/activities/AlreadyRegisteredActivity.java
client/client/src/main/java/org/wso2/iot/agent/events/listeners/ApplicationStateListener.java
client/client/src/main/java/org/wso2/iot/agent/events/listeners/RuntimeStateListener.java
client/client/src/main/java/org/wso2/iot/agent/events/publisher/HttpDataPublisher.java
client/client/src/main/java/org/wso2/iot/agent/services/LogPublisherFactory.java
client/client/src/main/java/org/wso2/iot/agent/services/PolicyComplianceChecker.java
client/client/src/main/java/org/wso2/iot/agent/services/PolicyOperationsMapper.java
client/client/src/main/java/org/wso2/iot/agent/services/PolicyRevokeHandler.java
client/client/src/main/java/org/wso2/iot/agent/services/location/LocationService.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManager.java
client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/APIController.java
client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/AccessTokenHandler.java
client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/RefreshTokenHandler.java
client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/utils/Constants.java

Improvements for location publishing, Access token renewal, Policy compliance and revocation

Improvements

---

client/client/src/main/java/org/wso2/iot/agent/events/listeners/ApplicationStateListener.java
client/client/src/main/java/org/wso2/iot/agent/services/PolicyRevokeHandler.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerDeviceOwner.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerWorkProfile.java
client/client/src/main/java/org/wso2/iot/agent/utils/Constants.java
client/client/src/main/res/values/strings.xml

Fixing https://github.com/wso2/product-iots/issues/1430

Fixing https://github.com/wso2/product-iots/issues/1430

---

client/client/src/main/res/layout/top_banner.xml
client/client/src/main/res/values/colors.xml

> Make the top banner text white lablable in the agent by refering to colors.xml
> Make the top banner text white lablable in the agent

making the top banner text white lablable

---

client/client/src/main/res/values/strings.xml

FIxing space prob in statment.

Adding space in statement

---

client/client/build.gradle

> Fixed build config issues in debugCope build variant.

Update build configs for cope

---

client/client/src/main/java/org/wso2/iot/agent/events/listeners/ApplicationStateListener.java

> Resolves #106
> Fixes an issue with the code where the 'equal' method has been called on a null object.

Fixing NPE occurring when installing application

---

client/client/build.gradle
client/client/src/main/AndroidManifest.xml
client/client/src/main/java/org/wso2/iot/agent/activities/ScreenShareActivity.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManager.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationProcessor.java
client/client/src/main/java/org/wso2/iot/agent/services/screenshare/ScreenImageReader.java
client/client/src/main/java/org/wso2/iot/agent/services/screenshare/ScreenSharingService.java
client/client/src/main/java/org/wso2/iot/agent/services/shell/RemoteShellExecutor.java
client/client/src/main/java/org/wso2/iot/agent/services/shell/RemoteShellTask.java
client/client/src/main/java/org/wso2/iot/agent/transport/exception/TransportHandlerException.java
client/client/src/main/java/org/wso2/iot/agent/transport/exception/TransportMessageFormatException.java
client/client/src/main/java/org/wso2/iot/agent/transport/websocket/AndroidWebSocketClient.java
client/client/src/main/java/org/wso2/iot/agent/transport/websocket/WebSocketSessionHandler.java
client/client/src/main/java/org/wso2/iot/agent/utils/Constants.java
client/client/src/main/res/values/strings.xml
system-service/app/src/main/AndroidManifest.xml
system-service/app/src/main/java/org/wso2/iot/system/service/SystemService.java
system-service/app/src/main/java/org/wso2/iot/system/service/api/InputEventHandler.java
system-service/app/src/main/java/org/wso2/iot/system/service/utils/Constants.java

> Merge https://github.com/wso2/cdmf-agent-android/pull/93 by resolving conflicts

Merge https://github.com/wso2/cdmf-agent-android/pull/93 by resolving conflicts

---

client/client/src/main/java/org/wso2/iot/agent/services/DeviceInfoPayload.java

> Fix for wso2/product-iots#1496

 Fix for wso2/product-iots#1496

---

client/client/build.gradle
client/iDPProxy/build.gradle

> Release IoT Android Agent 3.1.22 for IoTS-3.1.0-UPDATE7
https://github.com/wso2/product-iots/issues/1497

Fixed issues in build configs and increment agent version

---

client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/clients/OAuthSSLClient.java

https://github.com/wso2/cdmf-agent-android/issues/115

Handling issues in SSL flow

---

client/client/build.gradle
client/client/src/main/java/org/wso2/iot/agent/services/MessageProcessor.java
system-service/app/build.gradle

> Fix for wso2/product-iots#1503
Fix signing config issue in system service

Release agent 3.1.23

---

client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManager.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerBYOD.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerCOSU.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerDeviceOwner.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerOlderSdk.java

> Fix for https://github.com/wso2/product-iots/issues/1504

Fix for https://github.com/wso2/product-iots/issues/1504

---

client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerDeviceOwner.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationProcessor.java

Fix problem with restrictions in android device on device owner mode
I used this links:
https://developers.google.com/android/work/requirements/work-managed-device
https://github.com/googlesamples/android-testdpc

Owner device restrictions fix

---

client/client/src/main/java/org/wso2/iot/agent/services/AgentStartupReceiver.java
client/client/src/main/java/org/wso2/iot/agent/services/location/LocationService.java

> Fix for https://github.com/wso2/product-iots/issues/1521

Fixed https://github.com/wso2/product-iots/issues/1521

---

client/client/src/main/java/org/wso2/iot/agent/events/listeners/ApplicationStateListener.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerDeviceOwner.java

> Fix for issue https://github.com/wso2/product-iots/issues/1527

Fixed https://github.com/wso2/product-iots/issues/1527

---

client/client/build.gradle
client/client/src/main/java/org/wso2/iot/agent/events/listeners/ApplicationStateListener.java
client/client/src/main/java/org/wso2/iot/agent/services/PolicyRevokeHandler.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManager.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerBYOD.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerDeviceOwner.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerOlderSdk.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerWorkProfile.java
client/client/src/main/java/org/wso2/iot/agent/utils/Constants.java

> Fixed wso2/product-iots#1543

Fixed wso2/product-iots#1543

---

client/client/build.gradle
client/client/src/main/java/org/wso2/iot/agent/activities/AlreadyRegisteredActivity.java

> Preventing possible loop back in agent related to https://github.com/wso2/product-iots/issues/1558
Prepare for 3.1.25 release

Improvement for wso2/product-iots#1558

---

client/client/build.gradle

> Prepare for 3.1.27 Release
> Prepare for 3.1.27 Release
> Increment Agent version 
> N/A
> This release include necessary improvements and changes to apply Work Profile policy correctly and revoke it.
> N/A, No new features
> N/A, No new features
> N/A, No new features
> N/A, No new features
N/A, Can't automate tests
>  N/A, No new features
> No
> No
> Android Emulator, API 26
>  N/A, No new features

Prepare for 3.1.27 Release

---

client/client/build.gradle

> Prepare for 3.1.28 release
> Increment agent version for next release
> N/A
> N/A
- Improved location retrieval on devices which use Google play services by using Fused Location Client.
- Improvements to have server pulls with higher time intervals in order to prevent out of sync with the server when there is FCM service outage.
- Improvements to prevent simultaneous API calls to IoT Server upon arrival of multiple FCM notifications at once.
> N/A, prepare for release
> N/A, prepare for release
> N/A, prepare for release
> N/A, prepare for release
> N/A, prepare for release
- Confirmed that this PR doesn't commit any keys, …

 Prepare for 3.1.28 release

---

client/client/src/main/java/org/wso2/iot/agent/api/WiFiConfig.java
client/client/src/main/java/org/wso2/iot/agent/services/LocalNotification.java
client/client/src/main/java/org/wso2/iot/agent/services/PolicyRevokeHandler.java
client/client/src/main/java/org/wso2/iot/agent/services/location/LocationService.java

> Agent throwing NPEs and having location update bursts with physical devices. Optimizations done in this PR mitigate those issues.
> Mitigate NPE and location update burst issues in physical devices.
> Limit location update event rate. Fix possible NPEs. Check device owner and profile owner privileges to avoid security exceptions.
> N/A
> Mitigate NPE and location update burst issues in physical devices.
> N/A, bug fix without affecting functionality
> N/A, bug fix without affecting functionality
> N/A, bug fix without affecting functionality
> N/A
- Confirmed that this PR doesn't commit any keys, …

Improvements done to optimize for physical devices

---

client/client/build.gradle

> Prepare for 3.1.29 release
> Increment release version
> Update build gradle
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Up-gradable from 3.1.28
> Android 7.1.1 (API 25)
> N/A

Prepare for 3.1.29 release

---

client/client/src/main/java/org/wso2/emm/agent/api/ApplicationManager.java

> Modification to the fix for app uninstallation failure
> There's a possibility of a null pointer which was handled with this PR. 
> Added a pre check. Please refer the code changes.
> N/A bug fix
> N/A bug fix
> N/A bug fix
> N/A bug fix
> N/A bug fix
> N/A bug fix
- N/A
> Provide high-level details about the samples related to this feature
> https://github.com/wso2/cdmf-agent-android/pull/149/files
> N/A bug fix
> Android
> N/A bug fix

Modification to the fix for app uninstallation failure

---

client/client/src/main/java/org/wso2/emm/agent/api/ApplicationManager.java
client/client/src/main/java/org/wso2/emm/agent/services/MessageProcessor.java
client/client/src/main/java/org/wso2/emm/agent/utils/Constants.java
client/client/src/main/java/org/wso2/emm/agent/utils/Preference.java
client/client/src/main/res/values/strings.xml

> Fix for https://github.com/wso2/product-iots/issues/1678
When multiple application installation operations are placed once, some operations are stucked in IN_PROGRESS state and never move in to COMPLETE or ERROR status. This PR fix that issue.
> Prevent operation status being stuck in IN_PROGRESS state event application is successfully installed.
> Enhance deadlock prevention logic to maintain app installation states correctly though the app installation life cycle.
> N/A, Bug fix
>  Fixed https://github.com/wso2/product-iots/issues/1678
> N/A, Bug fix
> N/A, Bug fix
> N/A, Bug fix
> N/A, Bug fix
- …

Fix for https://github.com/wso2/product-iots/issues/1678

---

client/client/build.gradle
client/client/google-services.json
client/client/src/main/java/org/wso2/iot/agent/activities/DisclaimerActivity.java
client/client/src/main/java/org/wso2/iot/agent/activities/SplashActivity.java
client/client/src/main/java/org/wso2/iot/agent/activities/WorkProfileSelectionActivity.java
client/client/src/main/java/org/wso2/iot/agent/utils/Constants.java
client/client/src/main/res/values/strings.xml

> Add configurable disclaimer activity for GDPR
> To add configurable disclaimer activity for GDPR
> Add configurable disclaimer activity for GDPR
> N/A
> Added configurable disclaimer activity for GDPR
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Upgradable from 3.1.31
> Android API 27
> N/A

Add configurable disclaimer activity for GDPR

---

system-service/app/src/main/java/org/wso2/emm/system/service/EMMSystemService.java
system-service/app/src/main/java/org/wso2/emm/system/service/api/OTAServerManager.java
system-service/app/src/main/java/org/wso2/emm/system/service/utils/Constants.java

> Fix issue in firmware upgrade restarting upon firmware build date operation.
> Fix issue in firmware upgrade restarting upon firmware build date operation.
> Update system service to handle status properly.
> N/A
> Fix issue in firmware upgrade restarting upon firmware build date operation.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> No
> N/A
> Android API 23
> N/A

Fix issue in firmware upgrade restarting upon firmware build date operation

---

client/client/build.gradle
client/client/src/main/AndroidManifest.xml
client/client/src/main/java/org/wso2/iot/agent/AgentApplication.java
client/client/src/main/java/org/wso2/iot/agent/api/ApplicationManager.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManager.java

> Refactor code in PR #165 and add multi dex support
> Improve code quality and enable multi dex support
> Since Android L the device owner can install/uninstall packages using the PackageInstaller API which is utilized in this commit.
> N/A
> Allow silent app install/uninstall if agent is device owner
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> https://github.com/wso2/cdmf-agent-android/pull/165
> N/A
> JDK 1.8 Update 162
> Android Studio 3.0.1
> Tested on android 7.0
> N/A

 Code formatting PR #165 and enabling multi-dex

---

app-catalog/app/src/main/java/org/wso2/app/catalog/AppDetailsActivity.java
app-catalog/app/src/main/java/org/wso2/app/catalog/AppListActivity.java
app-catalog/app/src/main/java/org/wso2/app/catalog/adapters/ApplicationAdapter.java
app-catalog/app/src/main/java/org/wso2/app/catalog/utils/Constants.java
app-catalog/app/src/main/java/org/wso2/app/catalog/utils/PayloadParser.java
app-catalog/app/src/main/res/layout/activity_app_list.xml
app-catalog/app/src/main/res/values/strings.xml
system-service/app/src/main/java/org/wso2/iot/system/service/LockActivity.java
system-service/app/src/main/java/org/wso2/iot/system/service/MainActivity.java
system-service/app/src/main/java/org/wso2/iot/system/service/SystemService.java

- Fix issue in showing main activity after disabling the hard lock.
Steps to reproduce:
1. Trigger hard lock
2. Trigger any operation which displays a notification via System service (Eg. Firmware upgrade)
3. Trigger unlock
- Fix issue in installaing google play apps with app catalog
> Add fixes done in EMM 2.1.0 & 2.2.0
https://github.com/wso2/cdmf-agent-android/pull/178

Fixes from EMM 2.1.0 & 2.2.0 Agents

---

client/client/src/main/java/org/wso2/iot/agent/services/AlarmReceiver.java
client/client/src/main/java/org/wso2/iot/agent/utils/AlarmUtils.java

> Fixed issue in scheduled app installation on Android N and higher

Fixed issue in scheduled app installation on Android N and higher

---

client/client/src/main/java/org/wso2/emm/agent/services/operation/OperationManager.java

> provide a solution for the problem wso2/product-iots#1856
> Update the polling interval of the device with an API call for all the existing Android devices.

Restart the AlarmManager when polling interval change.

---

client/client/build.gradle
client/client/src/main/java/org/wso2/iot/agent/services/MessageProcessor.java
client/client/src/main/java/org/wso2/iot/agent/services/location/LocationService.java
client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManager.java
client/client/src/main/java/org/wso2/iot/agent/utils/Constants.java
client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/IdentityProxy.java
client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/utils/Constants.java

- Fixed issue in token renewal
- Add max token renewal failures before showing re authentication
- Minimize network calls for address fetching

 Fixes and optimizations for 3.3.1 release

---

client/client/src/main/AndroidManifest.xml
client/client/src/main/java/org/wso2/iot/agent/AgentApplication.java
client/client/src/main/java/org/wso2/iot/agent/AgentFileProvider.java
client/client/src/main/java/org/wso2/iot/agent/api/ApplicationManager.java

Fix issues in app install & uninstall

Fix issues in app install & uninstall
