- client/client/src/main/java/org/wso2/iot/agent/activities/AlreadyRegisteredActivity.java
- client/client/src/main/java/org/wso2/iot/agent/activities/AuthenticationActivity.java
The reason was when enrolling happens in the work-profile, the step of 'Granting Device Admin Permissions' is skipped as the agent already has the permissions. As a result of that, one preference flag that is saved in that step is not saved in the work-profile.
Work-around: If the agent is enrolling inside the work-profile, save the preference flag right after the enrollment is completed.
https://github.com/wso2/product-iots/issues/525
> Fixed for agent in work-profile requesting to re-login issue. 

- client/client/src/main/java/org/wso2/iot/agent/utils/Constants.java
Changed DATE_FORMAT for scheduled operations to match the date time format sent from IoT Server for scheduled app installs.
fixes [wso2/product-iots#791](https://github.com/wso2/product-iots/issues/791)
> Change DATE_FORMAT for scheduled operations

- client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/utils/Constants.java
The configurations related to keystores were read from Constants file instead of gradle
Moved configs to gradle
Docs were changed
https://docs.wso2.com/display/IoTS310/Generating+a+BKS+File+for+Android#GeneratingaBKSFileforAndroid-Step2:GeneratingaBKSfile
N/A
N/A, This is configs related to agent.
> changing configurations to be read from BuildConfig

- client/client/src/main/java/org/wso2/iot/agent/FCMMessagingService.java
- client/client/src/main/java/org/wso2/iot/agent/activities/AlreadyRegisteredActivity.java
- client/client/src/main/java/org/wso2/iot/agent/activities/RegistrationActivity.java
- client/client/src/main/java/org/wso2/iot/agent/events/publisher/HttpDataPublisher.java
In FCM, the message delivering order is causing an issue and the device enrollment fails. When the device enrollment request is sent by Android, an FCM request is sent to the device and since the enrollment response is not still received by the device, this causes synchronization issues.
Fixing FCM message flow. Fixes wso2/product-iots#1453
> FCM not working due to the message flow synchronization

- system-service/app/src/main/java/org/wso2/iot/system/service/api/OTAServerManager.java
- system-service/app/src/main/java/org/wso2/iot/system/service/utils/Constants.java
> Resume interrupted download of over-the-air (OTA), rather than restarting from 0 bytes during a retry. 
> During an OTA firmware package file download, that download should resume after a network interrupt occurs instead of restarting the download from the beginning (0th byte).
> Resume interrupted download of over-the-air (OTA)

- system-service/app/src/main/java/org/wso2/emm/system/service/api/OTAServerManager.java
- system-service/app/src/main/java/org/wso2/emm/system/service/utils/Constants.java
> Backport the "resume interrupted download of over-the-air (OTA)" functionality from IoTS 3.1.0 compatible system service to EMM 2.1.0 compatible system service
> Backport-Resume interrupted download of over-the-air (OTA)

- system-service/app/src/main/java/org/wso2/iot/system/service/api/OTAServerManager.java
- system-service/app/src/main/java/org/wso2/iot/system/service/utils/Constants.java
- system-service/app/src/main/java/org/wso2/iot/system/service/utils/FileUtils.java
- system-service/app/src/main/res/values/strings.xml
> Change request to the resume download feature
1. Currently the OTA firmware downloads will be saved in ../Download directory and this PR will change it to the location /cache/
2. Stop creating multiple download files during several calls of the firmware operation
3. Minor changes to the logic of the firmware download.
> Change Requests to Resume interrupted download of over-the-air (OTA)

- system-service/app/src/main/java/org/wso2/iot/system/service/api/OTAServerManager.java
- system-service/app/src/main/java/org/wso2/iot/system/service/utils/Constants.java
- system-service/app/src/main/java/org/wso2/iot/system/service/utils/FileUtils.java
> Change request to the resume download feature
1. Handle the /cache clearance in backwards compatible way
2. OTA firmware downloads will be saved in /cache/ota/
3. Handled the connection failures, timeouts when downloading the update package
4. Minor changes to the logic of the firmware download
> Change Requests fixes to Resume interrupted download of over-the-air

- system-service/app/src/main/java/org/wso2/iot/system/service/api/OTADownload.java
> This is to fix sending 'complete' status instead of 'error' when lower firmware version is OTA'ed.  Resolves https://github.com/wso2/product-iots/issues/1515
> Fix for sending 'Complete' status when lower version is OTA'ed

- client/client/src/main/java/org/wso2/iot/agent/AlertActivity.java
- client/client/src/main/java/org/wso2/iot/agent/api/WiFiConfig.java
- client/client/src/main/java/org/wso2/iot/agent/services/PolicyRevokeHandler.java
- client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManager.java
- client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerBYOD.java
- client/client/src/main/res/values/strings.xml
Issue related to Wifi compliance failing, ring operation not working and inability to stop the ring and minor other fixes
https://github.com/wso2/cdmf-agent-android/commit/83cad5dc41ee154f4ab903b1b77fd7922ede57a7
The agent app include a logic to increase the ringtone volume of a device if its muted. However, when playing the ringtone, the stream used is not the ringtone stream, and it has used notification stream. If the notification volume is muted, the ring will not be heard.
https://github.com/wso2/cdmf-agent-android/commit/15035664792de071d3d7f172b5efbd2e87f97b5f
WiFi API of Android which is used to return the currently connected WiFi network seems to return, the SSID wrapped in extra double quotes and this causes the compliance check to fail always. …
> Fixing Bugs related to ring operation and wifi operation

- client/client/src/main/java/org/wso2/emm/agent/WorkProfileManager.java
- client/client/src/main/java/org/wso2/emm/agent/api/ApplicationManager.java
- client/client/src/main/java/org/wso2/emm/agent/services/AlarmReceiver.java
- client/client/src/main/java/org/wso2/emm/agent/services/ApplicationManagementService.java
- client/client/src/main/java/org/wso2/emm/agent/services/MessageProcessor.java
- client/client/src/main/java/org/wso2/emm/agent/services/operation/OperationManager.java
- client/client/src/main/res/values/strings.xml
> In case of app uninstallation is called with invalid package name agent will checks and verify the given package name before uninstalling the application: Resolves https://github.com/wso2/product-iots/issues/1551
> Verifying package name before uninstalling an application

- client/client/src/main/java/org/wso2/iot/agent/activities/AuthenticationActivity.java
> When refresh token is expired, agent detects it and prompts the user to re-login to fetch new token pair. However, when the notification is tapped, the agent gets crashed.
> Split the stored username from "@" character and filled relevant text fields.
> Fixed wso2/product-iots#1558

- client/client/src/main/java/org/wso2/iot/agent/services/PolicyOperationsMapper.java
- client/client/src/main/java/org/wso2/iot/agent/services/PolicyRevokeHandler.java
- client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerWorkProfile.java
> When a policy with work profile restrictions (In this case system apps that have to be enabled in the work profile) is enabled the android error shows "Invalid operation code received: work profile". This PR fixed that issue and implement missing policy revoke flow for Work Profile policy.
https://github.com/wso2/product-iots/issues/1541
> Implement policy revoke flow for Work Profile policy and improve work profile policy enforcement.
> Modify PolicyRevokeHandler class to restore previous work profile state when Work Profile policy is removed.
> N/A, Bug fix
> This PR will include necessary improvements and changes to apply Work Profile policy correctly and revoke it.
> N/A, Bug fix
> N/A, Bug fix
> N/A, Bug fix
> N/A, Bug fix
N/A, cannot cover with automations
- Followed secure coding …
> Fix for https://github.com/wso2/product-iots/issues/1541

- client/client/build.gradle
- client/client/src/main/java/org/wso2/iot/agent/services/LocationUpdateReceiver.java
- client/client/src/main/java/org/wso2/iot/agent/services/location/LocationService.java
> In some android devices, location updates are only notified to location manager if location fetched via GPS. Passive location sources and network based location retrieval is not possible on those devices with native location manager in Android. However it is possible to retrieve passive & network based location via Fused Location Client provided with Google Play services. However it is not possible to use Fused Location Client on devices which don't have Google Play services. 
> Retrieve device location via Fused Location Client, if device has Google Play services. Otherwise get location via native Location Manager.
> Check the existence of Play Services on the device and use Fused Location Client, if Play Services available. Otherwise use Native Location Manager to retrieve location …
>  Retrieve location using FusedLocationClient on devices which have Google Play Services

- client/client/src/main/AndroidManifest.xml
- client/client/src/main/java/org/wso2/iot/agent/activities/AlreadyRegisteredActivity.java
- client/client/src/main/java/org/wso2/iot/agent/activities/AuthenticationActivity.java
- client/client/src/main/java/org/wso2/iot/agent/utils/Constants.java
- client/client/src/main/res/values/strings.xml
The mute operation makes Android N devices stop accepting any more commands.
fixing https://github.com/wso2/product-iots/issues/1614
Add the new permission required to mute device.
Added the permission necessery to gain access to do not disturb mode
N/A
Fixing the mute operation not working for Android N devices.
N/A
N/A
N/A
N/A
Covered with existing code
N/A
N/A
Migration for old to new devices is considered and it is handled by the code automatically.
> List all JDK versions, operating systems, databases, and …
> fixing https://github.com/wso2/product-iots/issues/1614

- client/client/build.gradle
- client/client/src/main/java/org/wso2/iot/agent/services/MessageProcessor.java
- client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/APIController.java
- client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/AccessTokenHandler.java
- client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/IdentityProxy.java
- client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/RefreshTokenHandler.java
- client/iDPProxy/src/main/java/org/wso2/iot/agent/proxy/utils/Constants.java
> Fix wso2/product-iots#1641
> Agent needs to prompt authentication failure notification when agent is unable to renew the token.
> Show notification to re authenticate if refresh token expired.
> N/A
> Improved agent to show a notification to re authenticate if refresh token expired.
> N/A, this is intuitive action taken by the agent
> N/A
> N/A, this is intuitive action taken by the agent
> N/A, this is intuitive action taken by the agent
> Unable to automate
> No
> No
> Up gradable from 3.1.29
> Android 7.1.1 API 25 x86 …
>  Fix for wso2/product-iots#1641

- client/client/src/main/java/org/wso2/emm/agent/api/ApplicationManager.java
- client/client/src/main/java/org/wso2/emm/agent/services/MessageProcessor.java
> This PR will fix the issue of app download stuck in IN_PROGRESS state. Further explaining, every time we trigger two or more enterprise INSTALL_APPLICATION operations in a row, the first operation does not come to a COMPLETED state even the app get installed successfully. For an example if we put three INSTALL_APPLICATION operations in a row, the first operation will be in IN_PROGRESS state while other two get updated to COMPLETED state.  Resolves https://github.com/wso2/product-iots/issues/1656
> After this fix if we put two or more INSTALL_APPLICATION operations in a row, all the operations will get updated to COMPLETED state.
> Change the the place where shared preference _app_install_id_'s value is set on the installApp method and remove the app installation attempt check.  
> …
> Fixes the issue of app download stuck in IN_PROGRESS state

- client/client/src/main/java/org/wso2/emm/agent/api/ApplicationManager.java
> This will fix the issue of app installation operations stuck in IN_PROGRESS status even though the application get installed on the device
> With this fix even though we put single or more INSTALL_APPLICATION operations in a row, all the operations will get updated to COMPLETED state.
> A user wants to see an  application installed status, whether it is successful or failed.
> N/A
> N/A
N/A
> N/A
> Fix the issue of app download stuck in IN_PROGRESS state

- client/client/src/main/java/org/wso2/emm/agent/api/ApplicationManager.java
> This will fix the issue of Android agent is returning the status "ERROR" with the message 'Package is not installed in the device or invalid package name' even though app is installed on the device. Resolves wso2/product-iots#1673
> This will enable enterprise silent app uninstallation on an enrolled device.
> The package name was incorrectly sent to the isPackageInstalled() method.
> Application is installed on the device. Schedule app uninstallation operation to the device. Verify the response from IoT Server. 
IoT server should return the status as "COMPLETED" if the uninstallation was triggered on an app that was installed in the device.
> N/A
> N/A
> N/A
- Ran …
> Fixed the issue with app uninstallation failure 

- client/client/src/main/java/org/wso2/emm/agent/api/ApplicationManager.java
- client/client/src/main/java/org/wso2/emm/agent/services/MessageProcessor.java
- client/client/src/main/java/org/wso2/emm/agent/services/SystemServiceResponseReceiver.java
> Fix for https://github.com/wso2/product-iots/issues/1678
When multiple application installation operations are placed once, some operations are stucked in IN_PROGRESS state and never move in to COMPLETE or ERROR status. This PR fix that issue.
> Prevent operation status being stuck in IN_PROGRESS state event application is successfully installed.
> Enhance deadlock prevention logic to maintain app installation states correctly though the app installation life cycle.
> N/A, Bug fix
>  Fixed https://github.com/wso2/product-iots/issues/1678
> N/A, Bug fix
> N/A, Bug fix
> N/A, Bug fix
> N/A, Bug fix
- …
> Fix for https://github.com/wso2/product-iots/issues/1678

- client/client/src/main/java/org/wso2/emm/agent/services/MessageProcessor.java
- system-service/app/src/main/java/org/wso2/emm/system/service/api/OTAServerManager.java
> After a total timeout(even thought the resumable download window has expired) of firmware upgrade operation OTA starts again from 0% until status is completed. Upgrade status was successful always. Status has to be Error when the time frame is expired. Resolves https://github.com/wso2/product-iots/issues/1692.
> Identified the second operation call for the same operation id and filter it to eliminate passing the firmware upgrade operation again to the system app. 
> Android agent's Message processor will listen to the second time system app call for the same operation and eliminate it.
> Send an OTA of Android OS to a device and device's network get disconnected while download is ongoing. Network failure stays until resumable download window expires. Once the networks reconnected on the …
> Fix for OTA resumable download continuing even after download window has expired. 

- client/client/build.gradle
- client/client/src/main/java/org/wso2/iot/agent/api/ApplicationManager.java
- client/client/src/main/java/org/wso2/iot/agent/services/PolicyRevokeHandler.java
- client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationManagerWorkProfile.java
- client/client/src/main/java/org/wso2/iot/agent/utils/CommonUtils.java
- client/client/src/main/java/org/wso2/iot/agent/utils/Constants.java
- client/gradle/wrapper/gradle-wrapper.properties
> Fix issue in install or update app in work profile via app manager.
> Allow user to install / update apps from app manager if policy permits to install apps from unknown sources.
> Configure unknown sources Secure Setting via device policy manager if current policy permits to install apps from unknown sources.
> N/A, bug fix
> Fixed https://github.com/wso2/product-iots/issues/1695
> N/A, Bug fix
> N/A, Bug fix
> N/A, Bug fix
> N/A, Bug fix
> N/A, Bug fix
> No
> Up-gradable from Agent 3.1.30
> Android API …
> Fixed https://github.com/wso2/product-iots/issues/1695

- client/client/build.gradle
Update package name from org.wso2.emm.system.service to org.wso2.iot.system.service,
https://github.com/wso2/cdmf-agent-android/blob/master/system-service/app/src/main/AndroidManifest.xml
> To Identify the system service properly from the release agent app. When I create a release build from the client app with a COPE mode and tried to login, it says the system service is not installed, even though I installed it.
> Release builds will work with COPE enabled devices.
> Just replaced the package name.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
>N/A 
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, …
> Update the package name of system service

- client/client/src/main/java/org/wso2/emm/agent/services/MessageProcessor.java
- client/client/src/main/java/org/wso2/emm/agent/utils/CommonUtils.java
- system-service/app/src/main/java/org/wso2/emm/system/service/api/OTAServerManager.java
> When a set of firmware upgrade operations triggered in a row only the first operation will continue while others are operations stale in IN_PROGRESS state. With this fix if Android agent receives set of firmware upgrade operations while the first is executing other operations will be marked as ERROR. fix wso2/product-iots#1716
> To eliminate firmware upgrade operations which were sent in a row being stale if not executed.
> Based on shared preferences controlled the logic of message processor. 
> Set of firmware upgrade operations were sent in a row. When checking the operations statuses it should reflect what actually happens to each of the operation that sent. 
> Fix wso2/product-iots#1716
> N/A
> N/A
> N/A
> N/A
- Can not automate
- Followed secure coding standards in …
> Enabling the capability to handle multiple upgrade firmware operations

- client/client/src/main/java/org/wso2/emm/agent/services/AlarmReceiver.java
- client/client/src/main/java/org/wso2/emm/agent/services/MessageProcessor.java
> Add lock to prevent multiple pending operation call in critical path
> Prevent having multiple pending operation calls simultaneously.
> Add in memory lock to prevent multiple pending operation call in critical path
> N/A
> Add lock to prevent multiple pending operation call in critical path
> N/A
> N/A
> N/A
> N/A
> N/A
> No
> Upgradable from previous release
> Android API 23
> N/A
> Add lock to prevent multiple pending operation call in critical path

- client/client/src/main/java/org/wso2/emm/agent/services/MessageProcessor.java
- client/client/src/main/java/org/wso2/emm/agent/utils/Constants.java
- system-service/app/src/main/java/org/wso2/emm/system/service/EMMSystemService.java
> Prevent OTA operations staling when System service stopped
> Prevent OTA operations staling when System service stopped
> Add time stamp based timeout to prevent OTA operations from staling.
> N/A
> Prevent OTA operations staling when System service stopped
> N/A
> N/A
> N/A
> N/A
> N/A
- Ran FindSecurityBugs plugin and verified report? yes/no
> N/A
> N/A
> Able to migrate from previous version
> Android 5.1
> N/A
> Prevent OTA operations staling when System service stopped

- client/client/src/main/java/org/wso2/emm/agent/services/MessageProcessor.java
> Agent handling firmware upgrade operations incorrectly whenever shared pref exists with firmware upgrade failure status. This is fixing that issue.
> Fixed operation staling issue in firmware upgrade
> Update firmware upgrade operation handling logic
> N/A
> Fixed operation staling issue in firmware upgrade
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Android 23
> N/A
> Fixed operation staling issue in firmware upgrade

- client/client/src/main/java/org/wso2/emm/agent/services/MessageProcessor.java
> Agent handling firmware upgrade operations incorrectly whenever shared pref exists with firmware upgrade failure status. This is fixing that issue.
> To fix operation staling issue in firmware upgrade
> Update firmware upgrade operation handling logic
> N/A
> Fixed operation staling issue in firmware upgrade
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Android 23
> N/A
> Fix for operation staling issue in firmware upgrade

- client/client/src/main/java/org/wso2/iot/agent/api/ApplicationManager.java
> Allow silent installation and uninstallation of packages if agent is device owner. User will still receive a notification upon installation/uninstallation.
> Allow users without system service to install and uninstall packages unattendedly.
> Since Android L the device owner can install/uninstall packages using the PackageInstaller API which is utilized in this commit.
> N/A
> Allow silent app install/uninstall if agent is device owner
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> Code coverage information
- Integration tests
> Details about the test cases and coverage
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, …
> Silent (un)install as device owner

- client/client/build.gradle
- client/client/src/main/java/org/wso2/iot/agent/activities/SplashActivity.java
The root detection need to happen prior to enrolling a device.
Close the agent if the device is rooted
Detect rooting in splash screen and close the agent
N/A
Detect rooting in splash screen and close the agent
N/A
N/A
N/A
N/A
- Unit tests 
> Code coverage information
- Integration tests
> Details about the test cases and coverage
N/A
N/A
N/A
Android 7.0
N/A
> Root detection for Android 

- system-service/app/src/main/AndroidManifest.xml
- system-service/app/src/main/java/org/wso2/emm/system/service/EMMSystemService.java
- system-service/app/src/main/java/org/wso2/emm/system/service/LockActivity.java
- system-service/app/src/main/java/org/wso2/emm/system/service/MainActivity.java
Fix issue in showing main activity after disabling the hard lock.
Steps to reproduce:
1. Trigger hard lock
2. Trigger any operation which displays a notification via System service (Eg. Firmware upgrade)
3. Trigger unlock
> Fix issue in showing main activity after disabling the hard lock.
> Fix issue in showing main activity after disabling the hard lock

- client/client/src/main/java/org/wso2/emm/agent/beans/Device.java
- client/client/src/main/java/org/wso2/emm/agent/services/DeviceInfoPayload.java
- client/client/src/main/java/org/wso2/emm/agent/services/DeviceNetworkStatus.java
- client/client/src/main/java/org/wso2/emm/agent/services/DeviceStartupIntentReceiver.java
- client/client/src/main/java/org/wso2/emm/agent/utils/CommonUtils.java
- client/client/src/main/java/org/wso2/emm/agent/utils/Constants.java
> Reduce the size of the device info payload by removing unchanged information comparing with the previously sent data.
> In the android agent create a Map, Which is storing key-value pairs for the attributes contains in the response payload and store that object in the shared preference. 
> At the time device info payload build, Compare the new values with the previous one and if changed add that to the device_info payload.
> Reducing DEVICE_INFO payload size by avoiding unchanged properties
